### ISSUE TITLE
table_middle icon states look off unless the table is surrounded by corner pieces

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#14175]
I don't like it

![image](https://cloud.githubusercontent.com/assets/19365096/23318076/f9195098-fa9e-11e6-8b50-703ba2de3a9d.png)

not at all

**Comment by Aurx** [comment]
The funniest part is that you could fix this with simple code and just one new sprite (per type of table).

**Comment by Probe1** [comment]
k do it

**Comment by ihadtoregisterforthis** [comment]
If you make them mesh like walls do, you end up with the same problem when the tables are not surrounded only by corner pieces

**Comment by Aurx** [comment]
Probie, I cannot into spriting.

**Comment by Exxion** [comment]
That is false
You would need sprites for every combination of present and absent corners, unless you want to use overlays

**Comment by Aurx** [comment]
Why would you not use overlays?

**Comment by Exxion** [comment]
They're annoying

**Comment by ghost** [comment]
"Simple code"

Literally adding diagonal sprites and cases to smoothwall, which would demultiply the amount of sprites we need to make

At this point, we might as well do it with overlays

**Comment by Exxion** [comment]
God
Every time I look at this issue, it bothers me more that the one for the regular metal table isn't even the right color
It's just a square
Color is the only thing they had to do
And they still fucked it up

**Comment by Bilgecrank** [comment]
[Here's the DMI!](https://github.com/vgstation-coders/vgstation13/files/1118395/Tables.zip) I wasn't sure how to put them in the DMI so I just stuck all of them in the same way.

Glass
![glass](https://user-images.githubusercontent.com/8432868/27777821-42bbd636-5f84-11e7-9ad5-0f1268b975c9.png)

Regular
![regular](https://user-images.githubusercontent.com/8432868/27777825-4f27a8fa-5f84-11e7-901c-e0968d35f5fb.png)

Poker
![poker](https://user-images.githubusercontent.com/8432868/27777827-53700b78-5f84-11e7-9673-7a0587ea8430.png)

Wooden
![wooden](https://user-images.githubusercontent.com/8432868/27777830-59a4b99e-5f84-11e7-8f81-b6342d3177da.png)

Reinforced
![reinforced](https://user-images.githubusercontent.com/8432868/27777835-61c7c33c-5f84-11e7-9a1d-12893ab48022.png)

In some of the sheets are all the original table sprites, the ones on the right are my addition, and are represented in the DMI. The *Center icons are the top row, and *CenterC3, *CenterC2, and *CenterC1 are the 3 corners, 2 corners, and 1 corners respectively.

**Comment by ihadtoregisterforthis** [comment]
Fixed but I can't find the PR or commit on github

**Comment by Shadowmech88** [comment]
Just tested locally, this is not fixed yet.
![image](https://user-images.githubusercontent.com/3991927/46271154-d1836d00-c510-11e8-833d-26635358e8ee.png)
