### ISSUE TITLE
You can just right-click to check for False Walls

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#30512]
![image](https://user-images.githubusercontent.com/7573912/132129323-3bd1fc16-cc18-4bde-8592-4dfe38171024.png)

**Comment by Exxion** [comment]
To the best of my knowledge this is completely impossible to fix without just removing right clicking.
But also, is it so bad that if you're really trying, you can see them? I think someone removed the typo from their examine text, but I thought that was a neat "feature", where you could see them if you paid really close attention. Also I'm pretty sure the typo was never removed from false *r*walls.

EDIT: Actually it could be fixed by making falsewalls into turfs instead of objects but that would be less than ideal

**Comment by DeityLink** [comment]
I've already fixed it

**Comment by Exxion** [comment]
Ah, right, `invisibility`. Still don't get why falsewalls must be completely indistinguishable from real walls without mesons, though.

**Comment by PrimeDSS13** [comment]
h-he's fast!
