### ISSUE TITLE
Vampire mode things

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3506]
~~Enthrall either never works or takes too long, waited over 5 minutes after I started enthralling and nothing happened.~~

~~Vampire cape is missing body sprite, it has an item sprite but shows up as a missing sprite on your character.~~

**Above were bugs and were fixed.**

You can't see list of your passive gained abilities, add them to notes.

Missing big red text about how you can regenerate in coffins, this is the most essential part of being a vampire.

Vampires get hungry despite being choke full of blood.

**Comment by CptWad** [comment]
>Vampires get hungry despite being choke full of blood.

Its better not to solve this as it can be a super-powergamer valid test strategy.
Changelings and nukeops can get hungry so theres no reason for vampires to not also need to eat.
Also keeps vampires looking somewhat normal

Everything else is a :+1:

**Comment by TermedClepe** [comment]
>Its better not to solve this as it can be a super-powergamer valid test strategy.

There's way better valid test methods for vampires, just drag them to space.

**Comment by clusterfack** [comment]
You could feed a vamp holy water, vamps are already extremely testable

**Comment by Intigracy** [comment]
1/2 are fixed, 3/4 aren't, not sure if 5 is intended or not.

I'll work on 3/4 soon-ish.

**Comment by Kurfursten** [comment]
@clusterfack The only remaining parts of this Issue are feature requests, not bugs.

**Comment by PJB3005** [comment]
Somebody say which of the things in this issue are still valid and are feature requests and I'll modify the main issue comment and change the tags.

**Comment by PJB3005** [comment]
Damnit mouse.

**Comment by Kurfursten** [comment]
1-2 were fixed, I'm sure of it and @Intigracy confirms above.
3-4 I believe haven't been implemented
5 was never intended.

**Comment by Intigracy** [comment]
I did 3.
