### ISSUE TITLE
Library guest computer

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#3656]
The search function doesn't seem to work.
No matter what criteria you put for the search, it just goes to the regular list of books

**Comment by d3athrow** [comment]
should be fixed with e59e09522bcd8500a46f97aa116f6394db8a6377

**Comment by NigglyWiggly** [comment]
Still doesn't work, but at least it goes to where a list of books SHOULD be now

**Comment by NigglyWiggly** [comment]
Fixed.
